name: CD

on:
  push:
    branches: [ development ]

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest tests/
    - name: Train and evaluate model
      run: |
        python -c "from app.model import ModelManager; mm = ModelManager(); mm.challenger_process()"
    - name: Merge to main
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git merge --no-ff development -m "Merge development into main"
        git push origin main
    - name: Showcase merge process
      run: |
        echo "Development branch merged to main branch"
        echo "All tests have passed"
        echo "Model training and evaluation successful"
        echo "Ready for deployment (if this were a real project)"